[package]
name = "catsay"
version = "0.1.0"
authors = ["Dae Choi <daechoi@outlook.com>"]
edition = "2021"

[dependencies]
structopt = "0.3.26"
colored = "2.1.0"
failure ="0.1.8"
exitfailure = "0.5.1"
predicates = "3.1.2"
assert_cmd = "2.0.16"